enum ActionTypes {
  FETCH_TODOS = "FETCH_TODOS",
  ADD_TODO = "ADD_TODO",
  REMOVE_TODO = "REMOVE_TODO",
  TOGGLE_TODO_ACTIVITY = "TOGGLE_TODO_ACTIVITY",
  UPDATE_TODO_VALUE = "UPDATE_TODO_VALUE",
  ACTIVATE_ALL_TODOS = "ACTIVATE_ALL_TODOS",
  COMPLETE_ALL_TODOS = "COMPLETE_ALL_TODOS",
  CLEAR_COMPLETED_TODOS = "CLEAR_COMPLETED_TODOS",
  UPDATE_FILTER_ACTIVITY_STATUS = "UPDATE_FILTER_ACTIVITY_STATUS",
  SET_ERROR = "SET_ERROR",
  REMOVE_ERROR = "REMOVE_ERROR",
}

export default ActionTypes;
