enum ActionTypes {
  ADD_TODO,
  REMOVE_TODO,
  TOGGLE_TODO_ACTIVITY,
  UPDATE_TODO_VALUE,
  ACTIVATE_ALL_TODOS,
  COMPLETE_ALL_TODOS,
  CLEAR_COMPLETED_TODOS,
  UPDATE_FILTER_ACTIVITY_STATUS,
}

export default ActionTypes;
