enum TodoActionTypes {
  // fetch todos

  GET_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS",
  GET_TODOS_REQUEST = "GET_TODOS_REQUEST",
  GET_TODOS_ERROR = "FETCH_TODOS_ERROR",

  // add todo

  ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS",
  ADD_TODO_REQUEST = "ADD_TODO_REQUEST",
  ADD_TODO_ERROR = "ADD_TODO_ERROR",

  // remove todo

  REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS",
  REMOVE_TODO_REQUEST = "REMOVE_TODO_REQUEST",
  REMOVE_TODO_ERROR = "REMOVE_TODO_ERROR",

  // toggle todo activity

  TOGGLE_TODO_ACTIVITY_SUCCESS = "TOGGLE_TODO_ACTIVITY_SUCCESS",
  TOGGLE_TODO_ACTIVITY_REQUEST = "TOGGLE_TODO_ACTIVITY_REQUEST",
  TOGGLE_TODO_ACTIVITY_ERROR = "TOGGLE_TODO_ACTIVITY_ERROR",

  // update todo

  UPDATE_TODO_VALUE_SUCCESS = "UPDATE_TODO_VALUE_SUCCESS",
  UPDATE_TODO_VALUE_REQUEST = "UPDATE_TODO_VALUE_REQUEST",
  UPDATE_TODO_VALUE_ERROR = "UPDATE_TODO_VALUE_ERROR",

  // activate all todos

  ACTIVATE_ALL_TODOS_SUCCESS = "ACTIVATE_ALL_TODOS_SUCCESS",
  ACTIVATE_ALL_TODOS_REQUEST = "ACTIVATE_ALL_TODOS_REQUEST",
  ACTIVATE_ALL_TODOS_ERROR = "ACTIVATE_ALL_TODOS_ERROR",

  // complete all todos

  COMPLETE_ALL_TODOS_SUCCESS = "COMPLETE_ALL_TODOS_SUCCESS",
  COMPLETE_ALL_TODOS_REQUEST = "COMPLETE_ALL_TODOS_REQUEST",
  COMPLETE_ALL_TODOS_ERROR = "COMPLETE_ALL_TODOS_ERROR",

  // clear completed todos

  CLEAR_COMPLETED_TODOS_SUCCESS = "CLEAR_COMPLETED_TODOS_SUCCESS",
  CLEAR_COMPLETED_TODOS_REQUEST = "CLEAR_COMPLETED_TODOS_REQUEST",
  CLEAR_COMPLETED_TODOS_ERROR = "CLEAR_COMPLETED_TODOS_ERROR",

  // remove todo error

  REMOVE_TODOS_ERROR = "REMOVE_TODOS_ERROR",
}

export default TodoActionTypes;
