enum UserActionTypes {
  // get current user

  GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS",
  GET_CURRENT_USER_REQUEST = "GET_CURRENT_USER_REQUEST",
  GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR",

  REMOVE_USER_ERROR = "REMOVE_USER_ERROR",
}

export default UserActionTypes;
